upstream backend {
  server nitro:3000;
}

server {
  listen 80;
  server_name localhost;

  index index.html;

  location / {
    #https://router.vuejs.org/guide/essentials/history-mode#nginx
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://backend/api;
  }
}